name: Node.js CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
<<<<<<< HEAD
        node-version: [18.x]
=======
        node-version: [10.x, 12.x, 14.x, 16.x]
>>>>>>> e944c23 (update node versions in the workflow)

    steps:
    - uses: actions/checkout@v2
    - run: sudo apt-get install -y yosys
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install
    - run: npm run build --if-present
    - run: npm test
      env:
        CI: true
